version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "10:00"
  open-pull-requests-limit: 10
  versioning-strategy: increase-if-necessary
  ignore:
  - dependency-name: webpack
    versions:
    - 5.24.3
    - 5.25.1
    - 5.34.0
  - dependency-name: css-loader
    versions:
    - 5.1.4
    - 5.2.3
  - dependency-name: underscore
    versions:
    - 1.13.0
  - dependency-name: chai
    versions:
    - 4.3.2
  - dependency-name: jquery
    versions:
    - 3.6.0
