language: node_js
node_js:
- stable
before_install:
- npm install -g npm
install: npm install
script:
- make
env:
  global:
    secure: M0L4ipU6ahd6CucnGdKMXxRhF+v3eWHo23Ab4ah0+jhNrbdC3NVYycr53Bur7Uuzy024LT8LmGfzi3B3bhprIkws7wf8jHRZ9pNUYFOsJDNz4Q413+BLJpI7rS9IJbtvnCm8v7+hu0OvlIvYvAHJRUaU7vGbsmuOqp3NxE9BB2yta/RGk2GYzjLcfm0BamPpFWafhjUeTKwr2IWRYBAeq6t03wJXFuju/FWnidyTKn0/bXYNzTbu9Ff2II2fl+WZTo8lOqf4WgTw5pj2qBbJVouL7iB+AXY56/1GczN9Ap7eDuu2dl/lRVoP+TKJ7wrIH7o+70wVU5n5FZoq5ICaQCA1OoDHPv/GU19m2zB7qd3WLd3htPRPhkuW+W1HKEQ9ovqmDsJea4qsER8annzT+D1eMaRFfV/kUU3hdUVfekCAvI7eoQfHnjFFHEtcqBASL2F3rL4EvY6FdxxtYOir1++5EpH4ouibJCQE+V8dqpUeF0FpR8ygq3nPy0saPNIjUIL/qK5nV/OKF5C9NY6Wl+uJhtByhGsnjt9l5r5U7og5yAx5+cw5nLjLC362sLFCSK0pCSoo9XCRjxgKlMesfReVGK/dzXfRI0W25Wt2IkA0Sk6ki2nnQPD8jjizrd11/YtTp9Ww0aVAzfulfNJzAr/GbjiOVD84r85CCxgqNWI=
